---
title: "pagedown-cv"
author: "Ethan Hurwitz"
date: "`r Sys.Date()`"
output:
  html_document:
    css: css/pagedown_cv_styles.css
---

# Welcome to my CV repository

If you're reading this, you may be like I was at one point. Realizing it had been several *years* since I last updated my CV. Overwhelmed at the thought of doing so. "Eh, it's not like anyone is reading this anyway!" Once you have the first member of your grad school cohort graduate though, you start getting that, "Shit... I need to get my stuff together" moment. After some quick googling, I realized there were ways to make this process much easier and less time consuming!

This repo builds off the work previously done by Nick Strayer with his [data-driven cv](http://nickstrayer.me/datadrivencv/) and Ulrik Lyngs' [modifications](https://github.com/ulyngs/pagedown-cv/). They created tools to build a cv with [`rmarkdown`](https://rmarkdown.rstudio.com) and [`pagedown`](https://github.com/rstudio/pagedown). Doing this made the cv creation/updating process much less of a PITA. Since the content and output are stored separately, we can make changes/additions to our cv data file without having to worry about changing all the layouts and generating process. All of that can be handled by `pagedown` and some `css` files that we'll rarely have to modify!

## How does it work?

Taken from Ulrik's Repo:

"Each document is generated by an R Markdown file that pulls in its content from **\_content/cv_entries.csv** and **\_content/publications.csv**.

The CSV files with the content are just local copies of the corresponding tabs in [a google sheet](https://docs.google.com/spreadsheets/d/1ta71CAGkcLqm-W1UdVRA_JJSddWV2TsrRZsCnQlmOis/edit?usp=sharing).

The R script **\_content/sync_w_gsheets.R** grabs the current content of the 'cv_entries' and the 'publications' tabs in the google sheet and stores it in the **\_content** folder."

I generally liked the layout and aesthetics of Ulrik's, however, I wanted to make some slight changes including formatting the references in proper APA format. The biggest change I wanted to make was setting up github actions so that the cv could be both automatically generated **and** updated on my website.

I host these files in this repository, and have set up github actions to periodically re-run the scripts that compile and generate my CV, and link the URL to the CV section of my website. Thus, all I have to do is add new information to that googlesheet, and my CV will be automatically updated! I simultaneously make my life easier and remove a large swath of the excuses I had for not keeping my CV updated! 

## How can I use it?
To use this for your own CV, download or clone this GitHub repo, or Ulrik's [original](https://github.com/ulyngs/pagedown-cv/) (in his, you will find other layouts as well).

After that, just update the content in the CSV files with your own cv data and tweak the **.Rmd** files as needed.
