on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'

name: update cv

jobs:
  updateCV:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      #GITHUB_PAT: ${{ secrets.GH_PAT}}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: install missing curl library
        run: |
            'sudo apt-get update -y && sudo apt-get libcurl4-openssl-dev -y'

      - uses: r-lib/actions/setup-renv@v1
      
      # - name: install packages missed by renv
      #   run: |
      #     R -e 'install.packages("bslib")'
      #     R -e 'install.packages("downlit")'
      #     R -e 'install.packages("xml2")'
      #     R -e 'install.packages("Lock5withR")'
      
      - name: Cache renv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Build site
        run: Rscript -e 'rmarkdown::render_site(quiet = TRUE)'
        
      - name: create PDF
        run: Rscript -e 'pagedown::chrome_print()'

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
