on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    # run every Sunday at 11 PM
    - cron: '0 23 * * 0'

name: update cv

jobs:
  updateCV:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      #GITHUB_PAT: ${{ secrets.GH_PAT}}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: install missing curl library
        run: |
            sudo apt-get install -y libcurl4-openssl-dev

#      - uses: r-lib/actions/setup-renv@v2

      - name: Setup Chrome
        uses: ShinnyaUeoka/setup-chrome@v1
        with:
          chrome-version: latest

      - name: install R packages
        run: |
          R -e 'install.packages("MASS")'
          R -e 'install.packages("Matrix")'
          R -e 'install.packages("lattice")'
          R -e 'install.packages("mgcv")'
          R -e 'install.packages("nlme")'
          R -e 'install.packages("AsioHeaders")'
          R -e 'install.packages("BH")'
          R -e 'install.packages("DBI")'
          R -e 'install.packages("R6")'
          R -e 'install.packages("RColorBrewer")'
          R -e 'install.packages("Rcpp")'
          R -e 'install.packages("RcppEigen")'
          R -e 'install.packages("askpass")'
          R -e 'install.packages("assertthat")'
          R -e 'install.packages("backports")'
          R -e 'install.packages("base64enc")'
          R -e 'install.packages("blob")'
          R -e 'install.packages("bookdown")'
          R -e 'install.packages("brio")'
          R -e 'install.packages("broom")'
          R -e 'install.packages("callr")'
          R -e 'install.packages("cellranger")'
          R -e 'install.packages("cli")'
          R -e 'install.packages("clipr")'
          R -e 'install.packages("colorspace")'
          R -e 'install.packages("colourpicker")'
          R -e 'install.packages("commonmark")'
          R -e 'install.packages("cpp11")'
          R -e 'install.packages("crayon")'
          R -e 'install.packages("curl")'
          R -e 'install.packages("dbplyr")'
          R -e 'install.packages("desc")'
          R -e 'install.packages("diffobj")'
          R -e 'install.packages("digest")'
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("ellipsis")'
          R -e 'install.packages("evaluate")'
          R -e 'install.packages("fansi")'
          R -e 'install.packages("farver")'
          R -e 'install.packages("fastmap")'
          R -e 'install.packages("forcats")'
          R -e 'install.packages("fs")'
          R -e 'install.packages("gargle")'
          R -e 'install.packages("generics")'
          R -e 'install.packages("ggplot2")'
          R -e 'install.packages("glue")'
          R -e 'install.packages("googledrive")'
          R -e 'install.packages("googlesheets4")'
          R -e 'install.packages("gtable")'
          R -e 'install.packages("haven")'
          R -e 'install.packages("here")'
          R -e 'install.packages("highr")'
          R -e 'install.packages("hms")'
          R -e 'install.packages("htmltools")'
          R -e 'install.packages("httpuv")'
          R -e 'install.packages("httr")'
          R -e 'install.packages("ids")'
          R -e 'install.packages("jquerylib")'
          R -e 'install.packages("jsonlite")'
          R -e 'install.packages("kableExtra")'
          R -e 'install.packages("knitr")'
          R -e 'install.packages("labeling")'
          R -e 'install.packages("later")'
          R -e 'install.packages("lifecycle")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("magrittr")'
          R -e 'install.packages("mime")'
          R -e 'install.packages("modelr")'
          R -e 'install.packages("munsell")'
          R -e 'install.packages("openssl")'
          R -e 'install.packages("pagedown")'
          R -e 'install.packages("pillar")'
          R -e 'install.packages("pkgbuild")'
          R -e 'install.packages("pkgconfig")'
          R -e 'install.packages("pkgload")'
          R -e 'install.packages("praise")'
          R -e 'install.packages("prettyunits")'
          R -e 'install.packages("processx")'
          R -e 'install.packages("progress")'
          R -e 'install.packages("promises")'
          R -e 'install.packages("ps")'
          R -e 'install.packages("purrr")'
          R -e 'install.packages("rappdirs")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("readxl")'
          R -e 'install.packages("rematch")'
          R -e 'install.packages("rematch2")'
          R -e 'install.packages("reprex")'
          R -e 'install.packages("rlang")'
          R -e 'install.packages("rmarkdown")'
          R -e 'install.packages("rprojroot")'
          R -e 'install.packages("rstudioapi")'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("scales")'
          R -e 'install.packages("selectr")'
          R -e 'install.packages("servr")'
          R -e 'install.packages("stringi")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("sys")'
          R -e 'install.packages("tibble")'
          R -e 'install.packages("tidyr")'
          R -e 'install.packages("tidyselect")'
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("tinytex")'
          R -e 'install.packages("utf8")'
          R -e 'install.packages("uuid")'
          R -e 'install.packages("vctrs")'
          R -e 'install.packages("viridis")'
          R -e 'install.packages("viridisLite")'
          R -e 'install.packages("waldo")'
          R -e 'install.packages("webshot")'
          R -e 'install.packages("whisker")'
          R -e 'install.packages("withr")'
          R -e 'install.packages("xfun")'
          R -e 'install.packages("xml2")'
          R -e 'install.packages("yaml")'
      
#       - name: install packages missed by renv
      #   run: |
      #     R -e 'install.packages("bslib")'
      #     R -e 'install.packages("downlit")'
      #     R -e 'install.packages("xml2")'
      #     R -e 'install.packages("Lock5withR")'
      
      - name: Cache renv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Build site
        run: Rscript -e 'rmarkdown::render_site(quiet = TRUE)'
        
      - name: create PDF
        run: Rscript -e 'pagedown::chrome_print(rmarkdown::render("Hurwitz_cv.Rmd"))'

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
